---
abstract: 'Enable to write validation rules in JavaScript'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FormValidator-Simple-Plugin-V8
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  FormValidator::Simple: 0
  JavaScript::V8: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/cho45/FormValidator-Simple-Plugin-V8.git
version: 0.01
